export const transactions = [
  {
    _id: "1",
    userId: "101",
    description: "Grocery shopping",
    paymentType: "Credit Card",
    category: "Food",
    amount: 50.75,
    location: "Walmart, NY",
    date: "2023-10-01",
  },
  {
    _id: "2",
    userId: "102",
    description: "Monthly rent",
    paymentType: "Bank Transfer",
    category: "Housing",
    amount: 1200.0,
    location: "New York, NY",
    date: "2023-10-01",
  },
  {
    _id: "3",
    userId: "103",
    description: "Gym membership",
    paymentType: "Debit Card",
    category: "Fitness",
    amount: 45.0,
    location: "Planet Fitness, CA",
    date: "2023-10-02",
  },
  {
    _id: "4",
    userId: "101",
    description: "Coffee with friends",
    paymentType: "Cash",
    category: "Entertainment",
    amount: 15.5,
    location: "Starbucks, NY",
    date: "2023-10-03",
  },
  {
    _id: "5",
    userId: "104",
    description: "Online course subscription",
    paymentType: "Credit Card",
    category: "Education",
    amount: 99.99,
    location: "Udemy, Online",
    date: "2023-10-04",
  },
  {
    _id: "6",
    userId: "102",
    description: "Gas refill",
    paymentType: "Debit Card",
    category: "Transportation",
    amount: 60.0,
    location: "Shell, TX",
    date: "2023-10-05",
  },
  {
    _id: "7",
    userId: "103",
    description: "Dinner at a restaurant",
    paymentType: "Credit Card",
    category: "Food",
    amount: 85.25,
    location: "Olive Garden, CA",
    date: "2023-10-06",
  },
  {
    _id: "8",
    userId: "104",
    description: "Movie tickets",
    paymentType: "Cash",
    category: "Entertainment",
    amount: 25.0,
    location: "AMC Theaters, NY",
    date: "2023-10-07",
  },
];

export const users = [
  {
    _id: "101",
    username: "john_doe",
    name: "John Doe",
    password: "password123",
    profilePicture: "https://example.com/profiles/john.jpg",
    gender: "Male",
  },
  {
    _id: "102",
    username: "jane_smith",
    name: "Jane Smith",
    password: "securepass456",
    profilePicture: "https://example.com/profiles/jane.jpg",
    gender: "Female",
  },
  {
    _id: "103",
    username: "mike_jones",
    name: "Mike Jones",
    password: "mypassword789",
    profilePicture: "https://example.com/profiles/mike.jpg",
    gender: "Male",
  },
  {
    _id: "104",
    username: "sarah_lee",
    name: "Sarah Lee",
    password: "pass1234",
    profilePicture: "https://example.com/profiles/sarah.jpg",
    gender: "Female",
  },
];
